---
- name: CONFIGURE OSPF ROUTING
  hosts: newsite
  gather_facts: false

  tasks:

  - name: Routing | Configure OSPF process
    cisco.ios.ios_ospfv2:
      config:
        processes: "{{ process_100_config | default([]) }}"
      state: merged
    vars:
      process_100_config: "{{ routing.ospf.processes | selectattr('process_id', 'eq', 100) }}"

  - name: Routing | Configure OSPFv2 interfaces
    cisco.ios.ios_ospf_interfaces:
      config: "{{ routing.ospf.interfaces }}"
      state: merged
