---
- name: CONFIGURE INTERFACES
  hosts: newsite
  gather_facts: false

  tasks:

  - name: Interfaces | Configure basic interface details
    cisco.ios.ios_interfaces:
      config: "{{ interfaces }}"
      state: merged

  - name: Interfaces | Configure layer 3 interface details
    cisco.ios.ios_l3_interfaces:
      config: "{{ l3_interfaces }}"
      state: merged
